import unittest
from app.clients.client_exception import ClientException


class TestClientException(unittest.TestCase):
    pass
