import unittest
from clients.client_exception import ClientException


class TestClientException(unittest.TestCase):
    pass
