from app.errors.base_error import BaseError


class ResourceNotInUseError(BaseError):
    pass
